config/routes.rb
Rails.application.routes.draw do

  root 'fold#index'

  resources :code
  resources :fold

end

app/models/Dashboard.rb
class Dashboard < ActiveRecord::Base
end

app/models/code.rb
class Code < ActiveRecord::Base
# add the necessary class methods, attributes, etc. here
  # to make the tests in spec/hangperson_game_spec.rb pass.
  attr_accessor :session_credentials
  # Get a word from remote "random word" service

  # def initialize()
  # end
  
  def initialize(session_credentials)
      @session_credentials = session_credentials
  end
  
  def listFile()
    # Gets list of remote files.
    @session_credentials.files
  end

end

app/models/fold.rb
class Fold < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/code_controller.rb
class CodeController < ApplicationController
  def code_params
    params.require(:code).permit(:name, :author, :code, :create_date, :parent)
  end

  def index
    @codes = Code.all
  end

  def new

  end

  def create

    params.require(:code)
    permitted = params[:code].permit(:name, :author, :code, :create_date, :parent)
    @code = Code.create!(permitted)
    @code.update_attributes(:parent => session[:current_fold_id])
    puts @code
    flash[:notice] = "#{@code.name} was successfully created."
    redirect_to fold_index_path
  end

  def edit
    @code = Code.find params[:id]
  end

  def update
     @code = Code.find params[:id]
     permitted = params[:code].permit(:name, :author, :code, :create_date, :parent)
     @code.update_attributes!(permitted)

     flash[:notice] = "#{@code.name} was successfully updated."
     redirect_to code_path(@code)
   end

  def show
    id = params[:id]
    @code = Code.find(id)
  end

  def destroy
    @code = Code.find(params[:id])
    @code.destroy
    flash[:notice] = "Code '#{@code.name}' deleted."
    redirect_to fold_index_path
  end

  def login
    #redirect_to code_index_path
  end
end

app/controllers/fold_controller.rb
class FoldController < ApplicationController
  def fold_params
    params.require(:fold).permit(:fold_name, :fold_author, :fold_create_date)
  end

  def index
    @folds = Fold.all
  end

  def show
    id = params[:id]
    @codes = Code.where(parent: id)
    @fold = Fold.find params[:id]
    session[:current_fold_id] = @fold.id
  end

  def new
  end

  def create
    params.require(:fold)
    permitted = params[:fold].permit(:fold_name, :fold_author, :fold_create_date)
    @fold = Fold.create!(permitted)
    flash[:notice] = "#{@fold.fold_name} was successfully created."
    redirect_to fold_index_path
  end


  def destroy
    id = params[:id]
    @fold = Fold.find(params[:id])
    Code.where(parent: id).each do |code|
      code.destroy
    end
    @fold.destroy
    flash[:notice] = "Fold '#{@fold.fold_name}' deleted."
    redirect_to fold_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/code_helper.rb
module CodeHelper
end

app/views/code/edit.html.haml
%h2 Edit code

= form_tag code_path(@code), :method => :put do

  = label :code, :name, 'Name'
  = text_field :code, 'name'

  = label :code, :author, 'Author'
  = text_field :code, 'author'

  = label :code, :code, 'Code'
  = text_field :code, 'code'

  = submit_tag 'Save Changes'

app/views/code/index.html.haml
%h1 All Codes

%table#codes
  %thead
    %tr
      %th Code Name
      %th Author
      %th Create Date
      %th More Info
  %tbody
    - @codes.each do |code|
      %tr
        %td= code.name
        %td= code.author
        %td= code.create_date
        %td= link_to "More about #{code.name}", code_path(code)

= link_to 'Add new code', new_code_path
= link_to 'Go To Fold List', fold_index_path

app/views/code/intro.html.haml
!!!
%html
  %head
    %link(rel="stylesheet" href="")
    %title Co-ding Platform
    = stylesheet_link_tag 'login'
    = csrf_meta_tags

  %body
    .wrapper
      .container
        %h1 Connect to your google drive!
        / Add buttons to initiate auth sequence and sign out
        // %button#authorize_button{:onclick='login'} Login
        = link_to 'Log in!', '/login'

app/views/code/login.html.haml
!!!
%html
  %head
    %link(rel="stylesheet" href="")
    %title Co-ding Platform
    = stylesheet_link_tag 'login'
    = csrf_meta_tags

  %body
    .wrapper
      .container
        %h1 Connect to your google drive!
        / Add buttons to initiate auth sequence and sign out
        %button#authorize_button{:style => "display: none;"} Authorize
        %button#signout_button{:style => "display: none;"} Sign Out
        %pre#content{:style => "white-space: pre-wrap;"}
        :javascript
          // Client ID and API key from the Developer Console
          var CLIENT_ID = '';
          var API_KEY = '';

          // Array of API discovery doc URLs for APIs used by the quickstart
          var DISCOVERY_DOCS = ["https://www.googleapis.com/discovery/v1/apis/drive/v3/rest"];

          // Authorization scopes required by the API; multiple scopes can be
          // included, separated by spaces.
          var SCOPES = 'https://www.googleapis.com/auth/drive.metadata.readonly';

          var authorizeButton = document.getElementById('authorize_button');
          var signoutButton = document.getElementById('signout_button');

          /**
           *  On load, called to load the auth2 library and API client library.
           */
          function handleClientLoad() {
            gapi.load('client:auth2', initClient);
          }

          /**
           *  Initializes the API client library and sets up sign-in state
           *  listeners.
           */
          function initClient() {
            gapi.client.init({
              apiKey: API_KEY,
              clientId: CLIENT_ID,
              discoveryDocs: DISCOVERY_DOCS,
              scope: SCOPES
            }).then(function () {
              // Listen for sign-in state changes.
              gapi.auth2.getAuthInstance().isSignedIn.listen(updateSigninStatus);

              // Handle the initial sign-in state.
              updateSigninStatus(gapi.auth2.getAuthInstance().isSignedIn.get());
              authorizeButton.onclick = handleAuthClick;
              signoutButton.onclick = handleSignoutClick;
            }, function(error) {
              appendPre(JSON.stringify(error, null, 2));
            });
          }

          /**
           *  Called when the signed in status changes, to update the UI
           *  appropriately. After a sign-in, the API is called.
           */
          function updateSigninStatus(isSignedIn) {
            if (isSignedIn) {
              authorizeButton.style.display = 'none';
              window.location.href = "fold"
              signoutButton.style.display = 'block';
              listFiles();
            } else {
              authorizeButton.style.display = 'block';
              signoutButton.style.display = 'none';
            }
          }

          /**
           *  Sign in the user upon button click.
           */
          function handleAuthClick(event) {
            gapi.auth2.getAuthInstance().signIn();
          }

          /**
           *  Sign out the user upon button click.
           */
          function handleSignoutClick(event) {
            gapi.auth2.getAuthInstance().signOut();
          }

          /**
           * Append a pre element to the body containing the given message
           * as its text node. Used to display the results of the API call.
           *
           * @param {string} message Text to be placed in pre element.
           */
          function appendPre(message) {
            var pre = document.getElementById('content');
            var textContent = document.createTextNode(message + '\n');
            pre.appendChild(textContent);
          }

          /**
           * Print files.
           */
          function listFiles() {
            gapi.client.drive.files.list({
              'pageSize': 10,
              'fields': "nextPageToken, files(id, name)"
            }).then(function(response) {
              appendPre('Files:');
              var files = response.result.files;
              if (files && files.length > 0) {
                for (var i = 0; i < files.length; i++) {
                  var file = files[i];
                  appendPre(file.name + ' (' + file.id + ')');
                }
              } else {
                appendPre('No files found.');
              }
            });
          }
        %script{:async => "", :defer => "defer", :onload => "this.onload=function(){};handleClientLoad()", :onreadystatechange => "if (this.readyState === 'complete') this.onload()", :src => "https://apis.google.com/js/api.js"}
          :cdata

app/views/code/new.html.haml
%h1 Create New Code

= form_tag code_index_path, :method => :post do

  = label :code, :name, 'Name'
  = text_field :code, 'name'

  = label :code, :author, 'Author'
  = text_field :code, 'author'

  = label :code, :create_date, 'Created On'
  = date_select :code, :create_date

  = label :code, :code, 'Code'
  = text_field :code, 'code'



  = submit_tag 'Save Changes'

app/views/code/show.html.haml
%h2 Details about #{@code.name}

%ul#details
  %li
    Author:
    = @code.author
  %li
    Created on:
    = @code.create_date.strftime("%B %d, %Y")

%h3 Code:

%p#description= @code.code


= link_to 'Edit code', edit_code_path(@code)
= link_to 'Back to fold list', fold_index_path
= link_to 'Delete', code_path(@code), :method => :delete

app/views/fold/index.html.haml
-#  This file is app/views/movies/index.html.haml
%h1 All Folds

%table#folds
  %thead
    %tr
      %th Fold Name
      %th Fold Author
      %th Fold Create Date
      %th files inside
  %tbody
    - @folds.each do |fold|
      %tr
        %td= fold.fold_name
        %td= fold.fold_author
        %td= fold.fold_create_date
        %td= link_to "More about #{fold.fold_name}", fold_path(fold)


= link_to 'Add new fold', new_fold_path

app/views/fold/new.html.haml
%h1 Create New Fold

= form_tag fold_index_path, :method => :post do

  = label :fold, :fold_name, 'Fold_Name'
  = text_field :fold, 'fold_name'

  = label :fold, :fold_author, 'Fold_Author'
  = text_field :fold, 'fold_author'

  = label :fold, :fold_create_date, 'Fold Created On'
  = date_select :fold, 'fold_create_date'




  = submit_tag 'Save Changes'

app/views/fold/show.html.haml
%h1 All Codes In This Fold

%table#codes
  %thead
    %tr
      %th Code Name
      %th Author
      %th Create Date
      %th More Info
  %tbody
    - @codes.each do |code|
      %tr
        %td= code.name
        %td= code.author
        %td= code.create_date
        %td= link_to "More about #{code.name}", code_path(code)

  = link_to 'Add new code  ', new_code_path
  = link_to 'Delete fold   ', fold_path(@fold), :method => :delete
  = link_to 'Back to fold list  ', fold_index_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title codeboard!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    - if flash[:notice]
      #notice.message= flash[:notice]
    - elsif flash[:warning]
      #warning.message= flash[:warning]
    #main
      = yield